"use client";
import { FormEvent, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { api, Activity, Trip } from "../../lib/api";
import { UserShell } from "../../components/user-shell";

const blank = { title: "", type: "", startTime: "", endTime: "", location: "", notes: "" };
export default function TripDetailPage() {
  const { id } = useParams<{ id: string }>(); const [trip, setTrip] = useState<Trip | null>(null); const [editing, setEditing] = useState(false); const [activity, setActivity] = useState(blank); const [dayId, setDayId] = useState<number | null>(null); const [editingId, setEditingId] = useState<number | null>(null); const [error, setError] = useState("");
  const load = () => api<Trip>(`/trips/${id}`).then(setTrip).catch((e) => setError(e.message)); useEffect(() => { void load(); }, [id]);
  async function saveTrip(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); try { await api(`/trips/${id}`, { method: "PUT", body: JSON.stringify(data) }); setEditing(false); load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update trip"); } }
  async function addDay() { try { await api(`/trips/${id}/days`, { method: "POST", body: "{}" }); load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to add day"); } }
  async function saveActivity(e: FormEvent) { e.preventDefault(); if (!dayId) return; try { const path = `/trips/${id}/days/${dayId}/activities${editingId ? `/${editingId}` : ""}`; await api(path, { method: editingId ? "PUT" : "POST", body: JSON.stringify(activity) }); setActivity(blank); setEditingId(null); load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save activity"); } }
  async function removeActivity(day: number, item: Activity) { try { await api(`/trips/${id}/days/${day}/activities/${item.id}`, { method: "DELETE" }); load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to delete activity"); } }
  if (!trip) return <UserShell title="Trip details" description="Loading your trip..." activePage="My Trips"><p className="text-slate-500">{error || "Loading..."}</p></UserShell>;
  return <UserShell title={trip.title} description={`${trip.destination}${trip.startDate ? ` · ${trip.startDate}` : ""}`} activePage="My Trips">
    {error && <p className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <div className="flex flex-wrap items-center justify-between gap-3"><div><span className="rounded-full bg-[#e4f3ef] px-3 py-1 text-xs font-semibold uppercase text-[#396c68]">{trip.status}</span><p className="mt-4 max-w-2xl text-slate-600">{trip.description || "No description yet. Add the feeling you want this trip to have."}</p></div><button onClick={() => setEditing(!editing)} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold">{editing ? "Close editor" : "Edit trip"}</button></div>
    {editing && <form onSubmit={saveTrip} className="mt-5 grid gap-3 rounded-2xl bg-slate-50 p-4 md:grid-cols-2">{[["title","Trip name",trip.title],["destination","Destination",trip.destination],["startDate","Start date",trip.startDate || ""],["endDate","End date",trip.endDate || ""],["budget","Budget",trip.budget?.toString() || ""]].map(([name,label,value]) => <label key={name} className="text-sm text-slate-600">{label}<input name={name} defaultValue={value} type={name.includes("Date") ? "date" : name === "budget" ? "number" : "text"} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2" /></label>)}<textarea name="description" defaultValue={trip.description} placeholder="Description" className="rounded-lg border border-slate-200 p-2 md:col-span-2" /><button className="rounded-lg bg-[#173f45] px-4 py-2 font-semibold text-white md:col-span-2">Save changes</button></form>}
    <section className="mt-8 border-t border-slate-100 pt-6"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#6b8a88]">Itinerary</p><h3 className="mt-1 text-2xl font-semibold">Days and activities</h3></div><button onClick={addDay} className="rounded-xl bg-[#dcefe9] px-4 py-2 text-sm font-semibold text-[#285b58]">+ Add day</button></div>
      <div className="mt-5 space-y-4">{trip.days.map((day) => <div key={day.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-center justify-between"><div><h4 className="font-semibold">Day {day.dayNumber}</h4><p className="text-sm text-slate-500">{day.date || "Date to be decided"}</p></div><button onClick={() => { setDayId(day.id); setEditingId(null); setActivity(blank); }} className="text-sm font-semibold text-[#396c68]">+ Activity</button></div><div className="mt-3 space-y-2">{day.activities.map((item) => <div key={item.id} className="flex items-start justify-between rounded-xl bg-slate-50 p-3"><div><p className="font-medium">{item.title}</p><p className="text-sm text-slate-500">{[item.startTime, item.location, item.type].filter(Boolean).join(" · ")}</p></div><div className="flex gap-3 text-xs font-semibold"><button onClick={() => { setDayId(day.id); setEditingId(item.id); setActivity({ title: item.title, type: item.type || "", startTime: item.startTime || "", endTime: item.endTime || "", location: item.location || "", notes: item.notes || "" }); }}>Edit</button><button className="text-red-700" onClick={() => removeActivity(day.id, item)}>Delete</button></div></div>)}</div></div>)}{trip.days.length === 0 && <p className="rounded-2xl border border-dashed border-slate-300 p-8 text-center text-slate-500">Add a day to begin your itinerary.</p>}</div>
    </section>
    {dayId && <form onSubmit={saveActivity} className="fixed inset-x-4 bottom-4 z-10 grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-2xl md:left-auto md:w-[420px]"><div className="flex justify-between"><h3 className="font-semibold">{editingId ? "Edit activity" : "New activity"}</h3><button type="button" onClick={() => setDayId(null)}>Close</button></div>{[["title","Activity name"],["type","Type"],["startTime","Start time"],["endTime","End time"],["location","Location"]].map(([name,label]) => <input key={name} required={name === "title"} placeholder={label} type={name.includes("Time") ? "time" : "text"} value={activity[name as keyof typeof activity]} onChange={(e) => setActivity({ ...activity, [name]: e.target.value })} className="rounded-lg border border-slate-200 px-3 py-2" />)}<textarea placeholder="Notes" value={activity.notes} onChange={(e) => setActivity({ ...activity, notes: e.target.value })} className="rounded-lg border border-slate-200 p-2" /><button className="rounded-lg bg-[#173f45] py-2 font-semibold text-white">Save activity</button></form>}
  </UserShell>;
}